version: '3'
services:
  locaweb-sorteio-dev:
    image: node:13.1.0
    ports:
      - 8080:8080
      - 3000:3000
    command: bash -c "yarn start"
    container_name: locaweb-sorteio-dev
    working_dir: /src
    volumes:
      - "../../.:/src"
    environment:
      HOST: 0.0.0.0
      APP_ENV: dev
      TERM: xterm-256color
