apiVersion: v1
kind: Service
metadata:
  name: locaweb-sorteio
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30030
  selector:
    app: locaweb-sorteio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locaweb-sorteio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locaweb-sorteio
  template:
    metadata:
      labels:
        app: locaweb-sorteio
    spec:
      containers:
      - name: locaweb-sorteio
        image: rsilvacluster/locaweb-sorteio
        env:
        - name: NODE_ENV
          value: "production"
        ports:
        - containerPort: 8080